---
name: Unit Tests

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore:
      - '**'
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master, dev]

###############
# Set the Job #
###############
jobs:
  UnitTest:
    name: Unit Test Cases
    # Set the agent to run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # Use the appropriate  Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -i https://test.pypi.org/simple/ python-osw-validation==0.0.3

      - name: Run unit tests
        run: |
          python test_report.py
          coverage run --source=src -m unittest discover -s tests/
          coverage report -m
          exit_status=$?
          
          # Set the exit status as an output for later use
          echo "::set-output name=exit_status::$exit_status"

      - name: Archive Coverage Report
        if: ${{ always() }}  # Upload the coverage report even if tests fail
        uses: actions/upload-artifact@v2
        with:
          name: htmlcov
          path: htmlcov
